version: '3'
services:
  web:
    build: ./
    image: docker.davidwbarratt.com/wzavala/willandjess
    env_file:
      - .env
  cache:
    image: davidbarratt/varnish
    environment:
      VIRTUAL_HOST: willandjess.us,www.willandjess.us,origin.willandjess.us
      LETSENCRYPT_HOST: willandjess.us,www.willandjess.us,origin.willandjess.us
    links:
      - web:backend
