<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130409203646 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE artist (artist_id BIGINT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(artist_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp (rsvp_id INT AUTO_INCREMENT NOT NULL, attending TINYINT(1) NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20) NOT NULL, adults INT NOT NULL, children INT NOT NULL, note LONGTEXT DEFAULT NULL, PRIMARY KEY(rsvp_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE rsvp_song (rsvp_id INT NOT NULL, song_id BIGINT NOT NULL, INDEX IDX_36F3E8F9EF80C8C2 (rsvp_id), INDEX IDX_36F3E8F9A0BDB2F3 (song_id), PRIMARY KEY(rsvp_id, song_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE song (song_id BIGINT NOT NULL, artist_id BIGINT DEFAULT NULL, title VARCHAR(255) NOT NULL, INDEX IDX_33EDEEA1B7970CF8 (artist_id), PRIMARY KEY(song_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE rsvp_song ADD CONSTRAINT FK_36F3E8F9EF80C8C2 FOREIGN KEY (rsvp_id) REFERENCES rsvp (rsvp_id)");
        $this->addSql("ALTER TABLE rsvp_song ADD CONSTRAINT FK_36F3E8F9A0BDB2F3 FOREIGN KEY (song_id) REFERENCES song (song_id)");
        $this->addSql("ALTER TABLE song ADD CONSTRAINT FK_33EDEEA1B7970CF8 FOREIGN KEY (artist_id) REFERENCES artist (artist_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE song DROP FOREIGN KEY FK_33EDEEA1B7970CF8");
        $this->addSql("ALTER TABLE rsvp_song DROP FOREIGN KEY FK_36F3E8F9EF80C8C2");
        $this->addSql("ALTER TABLE rsvp_song DROP FOREIGN KEY FK_36F3E8F9A0BDB2F3");
        $this->addSql("DROP TABLE artist");
        $this->addSql("DROP TABLE rsvp");
        $this->addSql("DROP TABLE rsvp_song");
        $this->addSql("DROP TABLE song");
    }
}
