parameters:
    will_and_jess_respond.twitter.class: WillAndJess\RespondBundle\Service\Twitter
    will_and_jess_respond.twitter.consumer_key: ~
    will_and_jess_respond.twitter.consumer_secret: ~
    will_and_jess_respond.twitter.access_key: ~
    will_and_jess_respond.twitter.access_key_secret: ~

services:
    will_and_jess_respond.twitter:
       class: %will_and_jess_respond.twitter.class%
       arguments: [@doctrine.orm.entity_manager, %will_and_jess_respond.twitter.consumer_key%, %will_and_jess_respond.twitter.consumer_secret%, %will_and_jess_respond.twitter.access_key%, %will_and_jess_respond.twitter.access_key_secret%]
